[project]
name = "cmeel-assimp"
version = "5.2.4"
description = "cmeel distribution for assimp, Open-Asset-Importer-Library Repository"
readme = "assimp/Readme.md"
requires-python = ">= 3.7"
license = "BSD-3-Clause"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-assimp"
repository = "https://github.com/cmake-wheel/cmeel-assimp.git"

[tool.cmeel]
source = "assimp"
build-number = 2

[build-system]
requires = ["cmeel[build]"]
build-backend = "cmeel.build"
