[build-system]
build-backend = "cmeel"
requires = ["cmeel-zlib", "cmeel[build]"]

[project]
dependencies = ["cmeel-zlib"]
description = "cmeel distribution for assimp, Open-Asset-Importer-Library Repository"
license = "BSD-3-Clause"
name = "cmeel-assimp"
requires-python = ">= 3.8"
version = "5.4.3.1"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-assimp"
repository = "https://github.com/cmake-wheel/cmeel-assimp.git"
upstream = "https://github.com/assimp/assimp"

[tool.cmeel]
configure-args = ["-DASSIMP_BUILD_ASSIMP_TOOLS=ON", "-DASSIMP_WARNINGS_AS_ERRORS=OFF"]
has-sitelib = false
source = "assimp"
upstream-version = "5.4.3"

[tool.tomlsort]
all = true
